In [1]:
import numpy as np
n1 = np.random.randint(1,100, size=10)
print("Random integers between 1 and 100:", n1)

Random integers between 1 and 100: [98 56 61 33 22  1 71 85 35 68]


In [3]:
print(np.max(n1))
print(np.min(n1))
print(np.mean(n1))
print(n1[n1 >= 40])
print(n1[n1 > 90])

98
1
53.0
[98 56 61 71 85 68]
[98]


In [13]:
n2 = n1 + 5
print(n2)
print(n2[np.clip(n2, 0, 100) < 100])
print(np.sort(n2))
print(n2[-3:])

[103  61  66  38  27   6  76  90  40  73]
[61 66 38 27  6 76 90 40 73]
[  6  27  38  40  61  66  73  76  90 103]
[90 40 73]
