In [2]:
import numpy as np
arr = np.ones((5, 5))
print(arr)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
n2 = np.arange(50, 101, 5)
print("Random integers between 1 and 100:", n2)

Random integers between 1 and 100: [ 1 11 21 31 41 51 61 71 81 91]


In [5]:
n3 = np.random.randint(1, 500, size=20)
print("Random integers between 1 and 100:", n3)

Random integers between 1 and 100: [484 217 355  32 493 348  76 458 202  70  68 319 437 177 408 456 144 134
 167 242]


In [9]:
n4 = np.random.randint(1, 25, size=24)
print("Random integers between 1 and 25:", n4)
arr = n4.reshape(4, 6)
print("Reshaped array (4x6):\n", arr)

Random integers between 1 and 25: [19  1 24  4  4 15 16  5  4  8 14  7  2 14  4 18 18  3 22  1  9 20 21 16]
Reshaped array (4x6):
 [[19  1 24  4  4 15]
 [16  5  4  8 14  7]
 [ 2 14  4 18 18  3]
 [22  1  9 20 21 16]]


In [13]:
import numpy as np

# Sample array containing numbers above and below 250
arr = np.array([120, 255, 80, 310, 245, 400, 190])

# Filter and print numbers greater than 250
greater_than_250 = arr[arr > 250]

print(greater_than_250)
# Output: [255 310 400]
n5 = greater_than_250.mean()
print("Mean of numbers greater than 250:", n5)

n6 = arr[[0,4,5]]
print("Selected elements at indices 0, 4, and 5:", n6)

[255 310 400]
Mean of numbers greater than 250: 321.6666666666667
Selected elements at indices 0, 4, and 5: [120 245 400]
